<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Order Request</title>
</head>
<body style="margin:0;padding:0;background:#f5f6f8;font-family:Arial, Helvetica, sans-serif;color:#111827;">
  <div style="max-width:680px;margin:0 auto;padding:24px;">

    <!-- Header -->
    <div style="background:#111827;color:#ffffff;padding:16px 18px;border-radius:10px 10px 0 0;">
      <div style="font-size:14px;opacity:0.9;">GIIB Web Portal</div>
      <div style="font-size:18px;font-weight:bold;margin-top:6px;">
        {{ !empty($order['sap_docnum']) ? 'Sales Order Created' : 'New Customer Order Request' }}
      </div>
      @if(!empty($order['sap_docnum']))
        <div style="margin-top:6px;font-size:13px;opacity:0.95;">
          SAP DocNum: <b>{{ $order['sap_docnum'] }}</b>
        </div>
      @endif
    </div>

    <!-- Card -->
    <div style="background:#ffffff;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 10px 10px;padding:18px;">

      <!-- Summary -->
      <div style="margin-bottom:14px;">
        <div style="font-size:14px;line-height:1.6;">
          <div><b>Customer:</b> {{ $order['customer_name'] ?? '-' }}</div>

          <div style="margin-top:4px;">
            <b>Company:</b>
            {{ $order['customer_company_name'] ?? '-' }}
            @if(!empty($order['customer_company_code']))
              ({{ $order['customer_company_code'] }})
            @endif
          </div>

          <div style="margin-top:4px;">
            <b>Requested Delivery Date:</b>
            {{ $order['requested_delivery_date'] ?? '-' }}
          </div>
        </div>
      </div>

      <!-- Items -->
      <div style="margin-top:10px;">
        <div style="font-size:14px;font-weight:bold;margin-bottom:8px;">Items</div>

        <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;font-size:13px;">
          <thead>
            <tr>
              <th align="left" style="padding:10px;border:1px solid #e5e7eb;background:#f9fafb;">#</th>
              <th align="left" style="padding:10px;border:1px solid #e5e7eb;background:#f9fafb;">Item Code</th>
              <th align="left" style="padding:10px;border:1px solid #e5e7eb;background:#f9fafb;">Description</th>
              <th align="right" style="padding:10px;border:1px solid #e5e7eb;background:#f9fafb;">Qty</th>
            </tr>
          </thead>
          <tbody>
            @php $lines = $order['lines'] ?? []; @endphp

            @forelse($lines as $i => $line)
              <tr>
                <td style="padding:10px;border:1px solid #e5e7eb;">{{ $i + 1 }}</td>
                <td style="padding:10px;border:1px solid #e5e7eb;">
                  {{ $line['itemCode'] ?? '-' }}
                </td>
                <td style="padding:10px;border:1px solid #e5e7eb;">
                  {{ $line['description'] ?? '-' }}
                </td>
                <td align="right" style="padding:10px;border:1px solid #e5e7eb;">
                  {{ $line['quantity'] ?? 0 }}
                </td>
              </tr>
            @empty
              <tr>
                <td colspan="4" style="padding:10px;border:1px solid #e5e7eb;color:#6b7280;">
                  No items found.
                </td>
              </tr>
            @endforelse
          </tbody>
        </table>
      </div>

      <!-- Footer -->
      <div style="margin-top:16px;font-size:12px;color:#6b7280;line-height:1.6;">
        This email was generated by GIIB Web Portal.
        @if(!empty($order['customer_email']))
          <div style="margin-top:6px;">
            Customer Email: {{ $order['customer_email'] }}
          </div>
        @endif
      </div>

    </div>

    <!-- Bottom small text -->
    <div style="text-align:center;margin-top:12px;font-size:11px;color:#9ca3af;">
      © {{ date('Y') }} GIIB
    </div>
  </div>
</body>
</html>
