<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Sales Order {{ $DocNum }}</title>
  <style>
    @page { margin: 10px 18px 16px 18px; }
    body { font-family: DejaVu Sans, Arial, Helvetica, sans-serif; font-size: 12px; color: #1f2937; margin-top: 0; }

    .muted { color: #6b7280; }
    .right { text-align: right; }
    .center { text-align: center; }
    .small { font-size: 11px; }
    .pre { white-space: pre-wrap; line-height: 1.35; }

    .mb-6 { margin-bottom: 6px; }
    .mb-8 { margin-bottom: 8px; }
    .mb-10 { margin-bottom: 10px; }

    .header {
      width: 100%;
      border: 1px solid #d1d5db;
      border-radius: 8px;
      padding: 8px 10px;
      margin-bottom: 8px;
    }
    .brand {
      font-weight: 700;
      font-size: 18px;
      color: #FF0000;
      letter-spacing: .3px;
      line-height: 1.1;
    }
    .header-table { width: 100%; border-collapse: collapse; }
    .header-table td { vertical-align: top; border: 0; padding: 0; }

    .doc-title {
      font-size: 16px;
      font-weight: 700;
      text-align: right;
      color: #FF0000;
      line-height: 1.1;
    }
    .doc-meta { text-align: right; line-height: 1.35; }

    .box {
      border: 1px solid #d1d5db;
      border-radius: 8px;
      padding: 8px 10px;
    }
    .label { font-weight: 600; color: #14532d; }
    .grid-table { width: 100%; border-collapse: collapse; }
    .grid-table td { border: 0; padding: 3px 0; }

    table.lines { width: 100%; border-collapse: collapse; }
    .lines th, .lines td { border: 1px solid #000000; padding: 6px 8px; }
    .lines thead th { background: #D3D3D3; color: #000000; font-weight: 700; }

    .totals {
      width: 300px;
      margin-left: auto;
      border: 1px solid #d1d5db;
      border-radius: 8px;
      padding: 8px 10px;
    }
    .totals td { padding: 6px 4px; }
    .totals .grand { font-weight: 700; color: #111827; border-top: 1px solid #e5e7eb; }

    .footer { margin-top: 12px; font-size: 11px; color: #6b7280; text-align: center; }
  </style>
</head>
<body>

  <!-- Header -->
  <div class="header">
    <table class="header-table">
      <tr>
        <td style="width:60%;">
          <div class="brand">GIIB GROUP</div>
          <div class="small muted">Sales Order generated by Customer Portal</div>
        </td>
        <td style="width:40%;">
          <div class="doc-title">SALES ORDER</div>
          <div class="doc-meta small">
            <div><span class="muted">Order No:</span> <strong>{{ $DocNum ?? '-' }}</strong></div>
            <div><span class="muted">Doc Entry:</span> {{ $DocEntry ?? '-' }}</div>
            <div><span class="muted">Status:</span> {{ $Status ?? '-' }}</div>
          </div>
        </td>
      </tr>
    </table>
  </div>

  <!-- Party / Dates -->
  <table class="grid-table mb-10">
    <tr>
      <td style="width:52%;">
        <div class="box">
          <div class="label mb-6">Customer</div>
          <div><strong>{{ $Customer ?? '-' }}</strong></div>
          <div class="muted small">BP Code: {{ $CardCode ?? '-' }}</div>
        </div>
      </td>
      <td style="width:4%"></td>
      <td style="width:44%;">
        <div class="box">
          <div class="label mb-6">Order Details</div>
          <table class="grid-table">
            <tr><td class="muted small" style="width:40%;">Order Date</td><td class="small">{{ $DocDate ?? '-' }}</td></tr>
            <tr><td class="muted small">Due Date</td><td class="small">{{ $DocDueDate ?? '-' }}</td></tr>
            <tr><td class="muted small">PO Number</td><td class="small">{{ $PONum ?? '-' }}</td></tr>
            <tr><td class="muted small">Currency</td><td class="small">{{ $Currency ?? 'MYR' }}</td></tr>
          </table>
        </div>
      </td>
    </tr>

    <!-- NEW ROW: Ship To & Bill To -->
    <tr>
      <td style="width:52%; padding-top:6px;">
        <div class="box">
          <div class="label mb-6">Ship To {{ $ShipToCode ? "({$ShipToCode})" : '' }}</div>
          <div class="pre small">{{ $ShipToText ?: '—' }}</div>
        </div>
      </td>
      <td style="width:4%"></td>
      <td style="width:44%; padding-top:6px;">
        <div class="box">
          <div class="label mb-6">Bill To {{ $PayToCode ? "({$PayToCode})" : '' }}</div>
          <div class="pre small">{{ $BillToText ?: '—' }}</div>
        </div>
      </td>
    </tr>
  </table>

  <!-- Lines -->
  <table class="lines">
    <thead>
      <tr>
        <th class="center" style="width:36px;">Qty</th>
        <th style="width:120px;">Item Code</th>
        <th>Description</th>
        <th class="right" style="width:90px;">Unit Price</th>
        <th class="right" style="width:100px;">Line Total</th>
      </tr>
    </thead>
    <tbody>
      @php
        $lines = $Lines ?? [];
        $fmt = function($n){ return number_format((float)$n, 2, '.', ','); };
      @endphp
      @forelse ($lines as $row)
        <tr>
          <td class="center">{{ $fmt($row['Quantity'] ?? 0) }}</td>
          <td>{{ $row['ItemCode'] ?? '-' }}</td>
          <td>{{ $row['Description'] ?? '-' }}</td>
          <td class="right">{{ $Currency ?? 'MYR' }} {{ $fmt($row['UnitPrice'] ?? 0) }}</td>
          <td class="right">{{ $Currency ?? 'MYR' }} {{ $fmt($row['LineTotal'] ?? 0) }}</td>
        </tr>
      @empty
        <tr><td colspan="5" class="center muted">No items available</td></tr>
      @endforelse
    </tbody>
  </table>

  <br>

  <!-- Totals -->
  <table class="totals">
    <tr><td>Subtotal</td><td class="right">{{ $Currency ?? 'MYR' }} {{ $fmt($Subtotal ?? 0) }}</td></tr>
    <tr><td>Discount</td><td class="right">- {{ $Currency ?? 'MYR' }} {{ $fmt($Discount ?? 0) }}</td></tr>
    <tr><td>VAT</td><td class="right">+ {{ $Currency ?? 'MYR' }} {{ $fmt($VAT ?? 0) }}</td></tr>
    <tr><td class="grand">Grand Total</td><td class="right grand">{{ $Currency ?? 'MYR' }} {{ $fmt($Grand ?? 0) }}</td></tr>
  </table>

  <div class="footer">Thank you for your business.</div>
</body>
</html>